INSERT INTO tenant_space.credentials  JSON '{
"accountPartition": "ABCD",
"region": "EU",
"country":"DE",
"account":"ABCD123",
"id":"unique",
"device_key": "ewogICAgImt0eSI6ICJFQyIsCiAgICAiY3J2IjogIlAtMjU2IiwKICAgICJ4IjogIlNiU3ZWTVhiQ242Z2VhTDdRdXNybUJNZ1NvbkQtb3JVZDVDVHRrS0tQZkEiLAogICAgInkiOiAidTNhc3dLVWxVYnhmY1FxS0lGSWRqaXZmUm5JRGt3NjdJOHVDRlI2ODZjMCIsCiAgICAiYWxnIjogIkVDREgtRVMrQTI1NktXIgp9",
"nonce":"55555",
"locked":false,
"signature":"MEYCIQDZ7xaOUumcAHRwWpxpLYcNHhX3mb3mBPG4K/94fid2cwIhAL8v2N/4dvbKHPhYkL4k5cC3kZ0bCidD+WJjxwUO9NQr"}';



