{{- $secretName := printf "%s-cassandra-credentials" .Release.Name -}}
{{- if eq (index .Values.podAnnotations "inject.xfsc.io/enabled") "true" }}
apiVersion: resources.xfsc.io/v1alpha1
kind: ResourceClaim
metadata:
  name: cassandra
  namespace: ocm-wstack
spec:
  type: cassandra

  providerRef:
    name: cassandra

  secretRef:
    name: {{ $secretName }}

  parameters:
    keyspace: ocm
    replicationFactor: 1
    durableWrites: true
    datacenter: dc1
{{- end }}