{{- if eq (index .Values.podAnnotations "inject.xfsc.io/enabled") "true" }}
apiVersion: resources.xfsc.io/v1alpha1
kind: ResourceProvider
metadata:
  name: storageservice
spec:
  type: storageservice
  scope: {{ .Values.resourceProvider.scope | quote }}
  description: {{ .Values.resourceProvider.description | quote }}
{{- with .Values.resourceProvider.allow.namespaces }}
  allow:
    namespaces:
{{ toYaml . | indent 6 }}
{{- end }}
  outputs:
    env:
      NATS_STORAGETOPIC: {{ .Values.config.messaging.storageTopic }}    
{{- end }}