name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    with: 
       build_args: --build-arg pluginRepoUrl=https://github.com/eclipse-xfsc/crypto-provider-hashicorp-vault-plugin \
                   --build-arg pluginTag=v1.3.0 \
       platforms: linux/amd64,linux/arm64
  helm:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm.yml@main